/* ++++++++++++++++++++++++++++++
  CREATE THE DATBASE
 +++++++++++++++++++++++++++++++ */

CREATE DATABASE [CertifiedOverheadCrane]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CertifiedOverheadCrane', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CertifiedOverheadCrane.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CertifiedOverheadCrane_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CertifiedOverheadCrane_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CertifiedOverheadCrane] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [CertifiedOverheadCrane] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET ARITHABORT OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET  READ_WRITE 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET  MULTI_USER 
GO
ALTER DATABASE [CertifiedOverheadCrane] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CertifiedOverheadCrane] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [CertifiedOverheadCrane]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [CertifiedOverheadCrane] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/* ++++++++++++++++++++++++++++++
  CREATE THE IIS USER
 +++++++++++++++++++++++++++++++ */

CREATE USER [OrchardCMS] FOR LOGIN [IIS APPPOOL\certifiedoverheadcrane] WITH DEFAULT_SCHEMA=[dbo]
GO

ALTER ROLE [db_datareader] ADD MEMBER [OrchardCMS]
GO

ALTER ROLE [db_datawriter] ADD MEMBER [OrchardCMS]
GO


